/**
 * An InputDetails object is generated by the InputDelegate, and contains relevant information about user input, such as controller buttons, keyboard keys, etc.
 */
package com.lowoui_as.component
{
	public class InputDetails
	{
		public var type:String;
		public var code:Number;
		public var value:*;
		public var navEquivalent:String;
		public var controllerIndex:uint;
		public var ctrlKey:Boolean;
		public var altKey:Boolean;
		public var shiftKey:Boolean
		
		public function InputDetails(type:String, code:Number, value:*, navEquivalent:String = null, controllerIndex:uint = 0, ctrlKey:Boolean = false, altKey:Boolean = false, shiftKey:Boolean = false)
		{
			this.type = type;
			this.code = code;
			this.value = value;
			this.navEquivalent = navEquivalent;
			this.controllerIndex = controllerIndex;
			this.ctrlKey = ctrlKey;
			this.altKey = altKey;
			this.shiftKey = shiftKey;
		}
		
		public function toString():String
		{
			return "[InputDetails code=" + code + ", type=" + type + " value=" + value + ", navEquivalent=" + navEquivalent + ", controllerIndex=" + controllerIndex + ", ctrlKey=" + ctrlKey + ", altKey=" + altKey + ", shiftKey=" + shiftKey + "]";
		}
	}
}